### ISSUE TITLE
Perf: test AWS Kinesis and Azure Event Hub channel providers

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/test-infra#78]
- [x] get familiar with the docs, tooling 
- [x] setup performance tests env
- [x] walk through the IMC test report
- [x] test AWS Kinesis channel provider
- [ ] test Azure Event Hub channel provider
- [x] prepare reports, open PR

**Comment by tzununbekov** [comment]
AWS Kinesis channel report:
https://github.com/triggermesh/test-infra/pull/119

I'm not aware if Azure Event Hubs channel provider is functional at the moment so it should be first tested for its relevance and then we can run performance tests. 

I'd close this issue and open a follow-up Event Hubs specific one if needed.
